name: flutter_windowmanager
description: A Flutter plugin for manipulating Android WindowManager LayoutParams.
version: 1.1.0

homepage: https://www.github.com/adaptant-labs/flutter_windowmanager
repository: https://www.github.com/adaptant-labs/flutter_windowmanager
issue_tracker: https://github.com/adaptant-labs/flutter_windowmanager/issues

environment:
  sdk: '>=3.0.0 <3.19.6'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: io.adaptant.labs.flutter_windowmanager
        pluginClass: FlutterWindowManagerPlugin
